CREATE TABLE IF NOT EXISTS TASK_MANAGEMENT_SYSTEM.ROLE(
       ID INT NOT NULL AUTO_INCREMENT,
       NAME VARCHAR(40) NOT NULL,
       DESCRIPTION VARCHAR(150) NOT NULL,
       CONSTRAINT pk_roles PRIMARY KEY (ID)
)