CREATE TABLE IF NOT EXISTS TASK_MANAGEMENT_SYSTEM.USER(
       ID INT(11) NOT NULL AUTO_INCREMENT,
       EMAIL VARCHAR(128) NOT NULL,
       FIRST_NAME VARCHAR(45) NOT NULL,
       LAST_NAME VARCHAR(45) NOT NULL,
       PASSWORD VARCHAR(64) NOT NULL,
        ENABLED BIT(1) NOT NULL,
       CONSTRAINT pk_roles PRIMARY KEY (ID)
)